name: easy_debounce
description: An extremely easy-to-use method call debouncer package for Dart/Flutter.
version: 2.0.2+1
homepage: https://github.com/magnuswikhog/easy_debounce

environment:
  sdk: ">=2.12.0 <3.0.0"

dev_dependencies:
  test: ^1.20.1
